import type { Pet } from './types';

export const pets: Pet[] = [
  {
    id: '1',
    name: 'Buddy',
    type: 'Dog',
    breed: 'Golden Retriever',
    age: 2,
    imageUrl: 'https://picsum.photos/seed/buddy/600/400',
    imageHint: 'golden retriever',
    description: 'Buddy is a friendly and playful Golden Retriever who loves to fetch and go for long walks. He is great with kids and other dogs.',
    healthStatus: 'Vaccinated, neutered, and microchipped.',
    careRequirements: ['Daily exercise', 'Regular grooming', 'Lots of love and attention'],
  },
  {
    id: '2',
    name: 'Whiskers',
    type: 'Cat',
    breed: 'Siamese',
    age: 3,
    imageUrl: 'https://picsum.photos/seed/whiskers/600/400',
    imageHint: 'siamese cat',
    description: 'Whiskers is a very vocal and affectionate Siamese cat. She loves to cuddle and will be your constant companion.',
    healthStatus: 'Vaccinated and spayed.',
    careRequirements: ['Clean litter box', 'Interactive toys', 'Cozy napping spots'],
  },
  {
    id: '3',
    name: 'Thumper',
    type: 'Rabbit',
    breed: 'Holland Lop',
    age: 1,
    imageUrl: 'https://picsum.photos/seed/thumper/600/400',
    imageHint: 'cute rabbit',
    description: 'Thumper is a curious and gentle Holland Lop. He enjoys hopping around and munching on fresh hay and vegetables.',
    healthStatus: 'Healthy and active.',
    careRequirements: ['Spacious hutch', 'Fresh hay and water daily', 'Safe toys for chewing'],
  },
  {
    id: '4',
    name: 'Kiwi',
    type: 'Bird',
    breed: 'Parakeet',
    age: 1,
    imageUrl: 'https://picsum.photos/seed/kiwi/600/400',
    imageHint: 'green parakeet',
    description: 'Kiwi is a cheerful and chatty parakeet. He loves to sing and can learn to mimic simple words. He enjoys company.',
    healthStatus: 'Healthy, wings lightly clipped for safety.',
    careRequirements: ['Large cage with toys', 'Fresh seeds, fruits, and vegetables', 'Daily interaction'],
  },
  {
    id: '5',
    name: 'Rocky',
    type: 'Dog',
    breed: 'German Shepherd',
    age: 4,
    imageUrl: 'https://picsum.photos/seed/rocky/600/400',
    imageHint: 'german shepherd',
    description: 'Rocky is a loyal and intelligent German Shepherd. He is highly trainable and would excel in an active home.',
    healthStatus: 'Vaccinated, neutered, and in excellent shape.',
    careRequirements: ['Regular training sessions', 'Plenty of mental stimulation', 'A strong leader'],
  },
  {
    id: '6',
    name: 'Luna',
    type: 'Cat',
    breed: 'Maine Coon',
    age: 5,
    imageUrl: 'https://picsum.photos/seed/luna/600/400',
    imageHint: 'fluffy cat',
    description: 'Luna is a gentle giant with a beautiful, fluffy coat. She is calm, gets along with everyone, and loves a good grooming session.',
    healthStatus: 'Vaccinated, spayed, and microchipped.',
    careRequirements: ['Regular brushing to prevent mats', 'Large scratching post', 'Affectionate companionship'],
  },
  {
    id: '7',
    name: 'Oreo',
    type: 'Rabbit',
    breed: 'Dutch',
    age: 2,
    imageUrl: 'https://picsum.photos/seed/oreo/600/400',
    imageHint: 'black white rabbit',
    description: 'Oreo is a sweet and social Dutch rabbit with classic black and white markings. He is litter-trained and loves to be petted.',
    healthStatus: 'Healthy and neutered.',
    careRequirements: ['Daily out-of-cage time for exercise', 'Variety of leafy greens', 'Soft bedding'],
  },
  {
    id: '8',
    name: 'Sunny',
    type: 'Bird',
    breed: 'Cockatiel',
    age: 3,
    imageUrl: 'https://picsum.photos/seed/sunny/600/400',
    imageHint: 'yellow cockatiel',
    description: 'Sunny is a bright and friendly cockatiel who loves to whistle tunes. He enjoys sitting on shoulders and getting head scratches.',
    healthStatus: 'Healthy and well-socialized.',
    careRequirements: ['Variety of perches', 'Nutrient-rich pellet diet', 'Out-of-cage playtime'],
  },
];
